name: Reusable Workflow with Matrix and Concurrency

on:
  workflow_call:

jobs:
  matrix_job:
    strategy:
      matrix:
        environment: [prod, stage, stage_ca, prod_ca]
        experience: [old, new]
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ matrix.environment }}-${{ matrix.experience }}
      cancel-in-progress: true
    steps:
      - name: Run task
        run: |
          echo "Running task for environment: ${{ matrix.environment }}"
          echo "Running task for experience: ${{ matrix.experience }}"
